/* Generated by Yosys 0.58 (git sha1 157aabb5831cc77d08346001c4a085f188d7c736, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "dnn_accelerator.v:7.1-159.10" *)
module dnn_accelerator(clk, rst_n, start, input_data_0, input_data_1, input_data_2, input_data_3, output_data_0, output_data_1, done, valid);
  (* src = "dnn_accelerator.v:8.11-8.14" *)
  input clk;
  wire clk;
  (* src = "dnn_accelerator.v:9.11-9.16" *)
  input rst_n;
  wire rst_n;
  (* src = "dnn_accelerator.v:10.11-10.16" *)
  input start;
  wire start;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  input [7:0] input_data_0;
  wire [7:0] input_data_0;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  input [7:0] input_data_1;
  wire [7:0] input_data_1;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  input [7:0] input_data_2;
  wire [7:0] input_data_2;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  input [7:0] input_data_3;
  wire [7:0] input_data_3;
  (* src = "dnn_accelerator.v:15.23-15.36" *)
  output [15:0] output_data_0;
  reg [15:0] output_data_0;
  (* src = "dnn_accelerator.v:16.23-16.36" *)
  output [15:0] output_data_1;
  reg [15:0] output_data_1;
  (* src = "dnn_accelerator.v:17.16-17.20" *)
  output done;
  wire done;
  (* src = "dnn_accelerator.v:18.16-18.21" *)
  output valid;
  reg valid;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _244_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _245_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _246_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _247_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _248_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _249_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _250_;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire _251_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _252_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _253_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _254_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _255_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _256_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _257_;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire _258_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _259_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _260_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _261_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _262_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _263_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _264_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _265_;
  (* src = "dnn_accelerator.v:11.17-11.29" *)
  wire _266_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _267_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _268_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _269_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _270_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _271_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _272_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _273_;
  (* src = "dnn_accelerator.v:12.17-12.29" *)
  wire _274_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _275_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _276_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _277_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _278_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _279_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _280_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _281_;
  (* src = "dnn_accelerator.v:13.17-13.29" *)
  wire _282_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _283_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _284_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _285_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _286_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _287_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _288_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _289_;
  (* src = "dnn_accelerator.v:14.17-14.29" *)
  wire _290_;
  (* src = "dnn_accelerator.v:33.15-33.24" *)
  wire _291_;
  (* src = "dnn_accelerator.v:33.15-33.24" *)
  wire _292_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _293_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _294_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _295_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _296_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _297_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _298_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _299_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _300_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _301_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _302_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _303_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _304_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _305_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _306_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _307_;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire _308_;
  (* src = "dnn_accelerator.v:32.15-32.25" *)
  wire _309_;
  (* src = "dnn_accelerator.v:32.15-32.25" *)
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:581.22-581.23" *)
  wire _466_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _467_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _468_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _469_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _470_;
  (* src = "dnn_accelerator.v:144.20-144.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _471_;
  (* src = "dnn_accelerator.v:144.20-144.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _472_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _473_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _474_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _475_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _476_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _477_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _478_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _479_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _480_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _481_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _482_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _483_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _484_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _485_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _486_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _487_;
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire _488_;
  (* src = "dnn_accelerator.v:9.11-9.16" *)
  wire _489_;
  (* src = "dnn_accelerator.v:10.11-10.16" *)
  wire _490_;
  (* src = "dnn_accelerator.v:31.15-31.20" *)
  wire _491_;
  (* src = "dnn_accelerator.v:31.15-31.20" *)
  wire _492_;
  (* src = "dnn_accelerator.v:31.15-31.20" *)
  wire _493_;
  (* force_downto = 32'd1 *)
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:581.22-581.23" *)
  (* unused_bits = "1" *)
  wire [1:0] _494_;
  (* force_downto = 32'd1 *)
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [1:0] _495_;
  (* force_downto = 32'd1 *)
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [1:0] _496_;
  (* force_downto = 32'd1 *)
  (* src = "dnn_accelerator.v:144.20-144.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [2:0] _497_;
  (* force_downto = 32'd1 *)
  (* src = "dnn_accelerator.v:118.20-118.20|dnn_accelerator.v:86.13-155.20|/opt/homebrew/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [15:0] _498_;
  (* src = "dnn_accelerator.v:24.16-24.27" *)
  wire [15:0] \bias_layer1[0] ;
  (* src = "dnn_accelerator.v:24.16-24.27" *)
  wire [15:0] \bias_layer1[1] ;
  (* src = "dnn_accelerator.v:24.16-24.27" *)
  wire [15:0] \bias_layer1[2] ;
  (* src = "dnn_accelerator.v:25.16-25.27" *)
  wire [15:0] \bias_layer2[0] ;
  (* src = "dnn_accelerator.v:25.16-25.27" *)
  wire [15:0] \bias_layer2[1] ;
  (* src = "dnn_accelerator.v:42.16-42.29" *)
  wire [7:0] current_input;
  (* src = "dnn_accelerator.v:43.16-43.30" *)
  wire [7:0] current_weight;
  (* src = "dnn_accelerator.v:33.15-33.24" *)
  reg [1:0] input_idx;
  (* src = "dnn_accelerator.v:44.17-44.24" *)
  wire [15:0] mac_out;
  (* src = "dnn_accelerator.v:28.16-28.26" *)
  reg [15:0] mac_result;
  (* src = "dnn_accelerator.v:32.15-32.25" *)
  reg [1:0] neuron_idx;
  (* src = "dnn_accelerator.v:31.15-31.20" *)
  reg [2:0] state;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[0] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[10] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[11] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[1] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[2] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[3] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[4] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[5] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[6] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[7] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[8] ;
  (* src = "dnn_accelerator.v:22.15-22.29" *)
  wire [7:0] \weights_layer1[9] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[0] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[1] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[2] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[3] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[4] ;
  (* src = "dnn_accelerator.v:23.15-23.29" *)
  wire [7:0] \weights_layer2[5] ;
  assign _311_ = ~_309_;
  assign _312_ = ~_291_;
  assign _313_ = ~_304_;
  assign _314_ = ~(_493_ | _491_);
  assign _466_ = _492_ & _314_;
  assign _315_ = ~_466_;
  assign _316_ = ~(_309_ | _310_);
  assign _317_ = _466_ & _316_;
  assign _318_ = _489_ & _292_;
  assign _243_ = _317_ & _318_;
  assign _319_ = _466_ & ~(_316_);
  assign _320_ = ~(_292_ & _319_);
  assign _242_ = _318_ & _319_;
  assign _321_ = ~(_491_ | _492_);
  assign _322_ = _493_ | ~(_321_);
  assign _471_ = ~_322_;
  assign _323_ = _491_ & ~(_493_);
  assign _472_ = _323_ & ~(_492_);
  assign _324_ = _492_ ? _314_ : _323_;
  assign _325_ = ~(_490_ | _322_);
  assign _237_ = _322_ ? _324_ : _490_;
  assign _326_ = _292_ & _291_;
  assign _327_ = ~_326_;
  assign _328_ = _292_ | ~(_466_);
  assign _329_ = _472_ | ~(_328_);
  assign _330_ = _327_ & _329_;
  assign _331_ = _237_ & ~(_319_);
  assign _238_ = _331_ & ~(_330_);
  assign _332_ = _493_ & _490_;
  assign _333_ = ~(_321_ & _332_);
  assign _334_ = ~(_317_ | _325_);
  assign _335_ = _333_ & _334_;
  assign _336_ = _310_ | ~(_472_);
  assign _337_ = _335_ & _336_;
  assign _239_ = _337_ & ~(_330_);
  assign _338_ = _466_ ? _292_ : _321_;
  assign _241_ = _335_ & _338_;
  assign _240_ = _320_ & _237_;
  assign _339_ = _292_ | _291_;
  assign _340_ = _291_ & ~(_292_);
  assign _341_ = ~(_267_ & _340_);
  assign _342_ = ~(_283_ & _326_);
  assign _343_ = _291_ | ~(_275_);
  assign _344_ = _342_ & _343_;
  assign _345_ = ~(_341_ & _344_);
  assign _346_ = _292_ & ~(_291_);
  assign _244_ = _339_ ? _345_ : _259_;
  assign _347_ = ~(_268_ & _340_);
  assign _348_ = ~(_284_ & _326_);
  assign _349_ = _291_ | ~(_276_);
  assign _350_ = _348_ & _349_;
  assign _351_ = ~(_347_ & _350_);
  assign _245_ = _339_ ? _351_ : _260_;
  assign _352_ = ~(_269_ & _340_);
  assign _353_ = ~(_285_ & _326_);
  assign _354_ = _291_ | ~(_277_);
  assign _355_ = _353_ & _354_;
  assign _356_ = ~(_352_ & _355_);
  assign _246_ = _339_ ? _356_ : _261_;
  assign _357_ = ~(_286_ & _326_);
  assign _358_ = ~(_270_ & _340_);
  assign _359_ = _291_ | ~(_278_);
  assign _360_ = _358_ & _359_;
  assign _361_ = ~(_357_ & _360_);
  assign _247_ = _339_ ? _361_ : _262_;
  assign _362_ = ~(_271_ & _340_);
  assign _363_ = ~(_287_ & _326_);
  assign _364_ = _291_ | ~(_279_);
  assign _365_ = _363_ & _364_;
  assign _366_ = ~(_362_ & _365_);
  assign _248_ = _339_ ? _366_ : _263_;
  assign _367_ = ~(_272_ & _340_);
  assign _368_ = ~(_288_ & _326_);
  assign _369_ = _291_ | ~(_280_);
  assign _370_ = _368_ & _369_;
  assign _371_ = ~(_367_ & _370_);
  assign _249_ = _339_ ? _371_ : _264_;
  assign _372_ = ~(_289_ & _326_);
  assign _373_ = ~(_273_ & _340_);
  assign _374_ = _291_ | ~(_281_);
  assign _375_ = _373_ & _374_;
  assign _376_ = ~(_372_ & _375_);
  assign _250_ = _339_ ? _376_ : _265_;
  assign _377_ = ~(_290_ & _326_);
  assign _378_ = ~(_274_ & _340_);
  assign _379_ = _291_ | ~(_282_);
  assign _380_ = _378_ & _379_;
  assign _381_ = ~(_377_ & _380_);
  assign _251_ = _339_ ? _381_ : _266_;
  assign _382_ = _309_ ^ _310_;
  assign _383_ = ~(_292_ & _382_);
  assign _384_ = ~(_292_ ^ _382_);
  assign _385_ = ~(_309_ & _291_);
  assign _386_ = ~(_309_ | _291_);
  assign _387_ = _385_ & ~(_386_);
  assign _388_ = _309_ | ~(_310_);
  assign _389_ = _292_ | _388_;
  assign _390_ = _309_ & ~(_310_);
  assign _391_ = _310_ | ~(_309_);
  assign _392_ = ~(_309_ & _292_);
  assign _393_ = _292_ ? _391_ : _388_;
  assign _394_ = _387_ & _393_;
  assign _395_ = _384_ | _385_;
  assign _396_ = _384_ ^ _385_;
  assign _397_ = ~(_393_ & _396_);
  assign _398_ = _384_ | ~(_394_);
  assign _399_ = ~(_346_ & _390_);
  assign _400_ = _395_ & _399_;
  assign _401_ = ~(_398_ & _400_);
  assign _402_ = _472_ & _390_;
  assign _252_ = _472_ ? _390_ : _401_;
  assign _403_ = ~(_384_ & _394_);
  assign _404_ = _397_ & _403_;
  assign _405_ = ~(_397_ & _403_);
  assign _406_ = ~(_400_ & _404_);
  assign _407_ = _472_ | ~(_399_);
  assign _408_ = _397_ & ~(_407_);
  assign _409_ = ~(_406_ & _408_);
  assign _410_ = _310_ ? _386_ : _291_;
  assign _411_ = ~(_472_ & _410_);
  assign _253_ = _409_ & _411_;
  assign _412_ = _326_ | ~(_339_);
  assign _413_ = ~_412_;
  assign _414_ = ~(_390_ & _412_);
  assign _415_ = _389_ & _414_;
  assign _416_ = ~(_316_ & _413_);
  assign _417_ = ~(_415_ & _416_);
  assign _254_ = _472_ ? _417_ : _405_;
  assign _418_ = _310_ ? _311_ : _387_;
  assign _419_ = ~(_413_ & _418_);
  assign _420_ = _384_ & _387_;
  assign _255_ = _472_ ? _419_ : _420_;
  assign _421_ = ~(_472_ | _394_);
  assign _422_ = ~(_406_ & _421_);
  assign _258_ = ~_422_;
  assign _423_ = ~(_340_ & _382_);
  assign _424_ = _472_ & _423_;
  assign _425_ = ~(_416_ & _424_);
  assign _256_ = _422_ & _425_;
  assign _426_ = ~(_316_ & _326_);
  assign _427_ = _472_ & _426_;
  assign _428_ = ~(_383_ & _427_);
  assign _257_ = _422_ & _428_;
  assign _467_ = _312_ & _329_;
  assign _468_ = _329_ & _413_;
  assign _429_ = _315_ & _336_;
  assign _469_ = _311_ & ~(_429_);
  assign _470_ = _382_ & ~(_429_);
  assign _473_ = _293_ & _330_;
  assign _430_ = _292_ | _300_;
  assign _431_ = ~(_466_ & _430_);
  assign _432_ = ~(_310_ & _326_);
  assign _433_ = _326_ ? _310_ : _300_;
  assign _434_ = ~(_472_ & _433_);
  assign _480_ = ~(_431_ & _434_);
  assign _435_ = _301_ | _326_;
  assign _436_ = ~(_427_ & _435_);
  assign _437_ = _292_ ? _309_ : _301_;
  assign _438_ = ~_437_;
  assign _439_ = _466_ ? _438_ : _472_;
  assign _481_ = ~(_436_ & _439_);
  assign _440_ = _292_ ? _311_ : _302_;
  assign _441_ = ~(_466_ & _440_);
  assign _442_ = _302_ | _326_;
  assign _443_ = _472_ & _442_;
  assign _444_ = ~(_432_ & _443_);
  assign _482_ = ~(_441_ & _444_);
  assign _445_ = _292_ | _303_;
  assign _446_ = ~(_466_ & _445_);
  assign _447_ = _326_ ? _310_ : _303_;
  assign _448_ = ~(_472_ & _447_);
  assign _483_ = ~(_446_ & _448_);
  assign _449_ = _304_ | _326_;
  assign _450_ = ~(_326_ & _391_);
  assign _451_ = _472_ & _449_;
  assign _452_ = ~(_450_ & _451_);
  assign _453_ = _466_ & _392_;
  assign _454_ = _292_ ? _309_ : _313_;
  assign _455_ = _466_ ? _454_ : _472_;
  assign _484_ = ~(_452_ & _455_);
  assign _456_ = _292_ | _305_;
  assign _457_ = _453_ & _456_;
  assign _458_ = _326_ ? _316_ : _305_;
  assign _459_ = _472_ ? _458_ : _315_;
  assign _485_ = _457_ | _459_;
  assign _460_ = _292_ | _306_;
  assign _461_ = ~(_466_ & _460_);
  assign _462_ = _326_ ? _391_ : _306_;
  assign _463_ = ~(_472_ & _462_);
  assign _486_ = ~(_461_ & _463_);
  assign _464_ = ~(_307_ & _330_);
  assign _465_ = ~(_326_ & _402_);
  assign _487_ = ~(_464_ & _465_);
  assign _488_ = _308_ & _330_;
  assign _474_ = _294_ & _330_;
  assign _475_ = _295_ & _330_;
  assign _476_ = _296_ & _330_;
  assign _477_ = _297_ & _330_;
  assign _478_ = _298_ & _330_;
  assign _479_ = _299_ & _330_;
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) input_idx[0] <= 1'h0;
    else if (_000_) input_idx[0] <= _495_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) input_idx[1] <= 1'h0;
    else if (_000_) input_idx[1] <= _495_[1];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[0] <= mac_out[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[1] <= mac_out[1];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[2] <= mac_out[2];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[3] <= mac_out[3];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[4] <= mac_out[4];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[5] <= mac_out[5];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[6] <= mac_out[6];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[7] <= mac_out[7];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[8] <= mac_out[8];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[9] <= mac_out[9];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[10] <= mac_out[10];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[11] <= mac_out[11];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[12] <= mac_out[12];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[13] <= mac_out[13];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[14] <= mac_out[14];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_006_) output_data_0[15] <= mac_out[15];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[0] <= mac_out[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[1] <= mac_out[1];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[2] <= mac_out[2];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[3] <= mac_out[3];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[4] <= mac_out[4];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[5] <= mac_out[5];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[6] <= mac_out[6];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[7] <= mac_out[7];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[8] <= mac_out[8];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[9] <= mac_out[9];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[10] <= mac_out[10];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[11] <= mac_out[11];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[12] <= mac_out[12];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[13] <= mac_out[13];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[14] <= mac_out[14];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk)
    if (_005_) output_data_1[15] <= mac_out[15];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) valid <= 1'h0;
    else if (_004_) valid <= _494_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[0] <= 1'h0;
    else if (_003_) mac_result[0] <= _498_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[1] <= 1'h0;
    else if (_003_) mac_result[1] <= _498_[1];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[2] <= 1'h0;
    else if (_003_) mac_result[2] <= _498_[2];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[3] <= 1'h0;
    else if (_003_) mac_result[3] <= _498_[3];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[4] <= 1'h0;
    else if (_003_) mac_result[4] <= _498_[4];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[5] <= 1'h0;
    else if (_003_) mac_result[5] <= _498_[5];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[6] <= 1'h0;
    else if (_003_) mac_result[6] <= _498_[6];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[7] <= 1'h0;
    else if (_003_) mac_result[7] <= _498_[7];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[8] <= 1'h0;
    else if (_003_) mac_result[8] <= _498_[8];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[9] <= 1'h0;
    else if (_003_) mac_result[9] <= _498_[9];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[10] <= 1'h0;
    else if (_003_) mac_result[10] <= _498_[10];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[11] <= 1'h0;
    else if (_003_) mac_result[11] <= _498_[11];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[12] <= 1'h0;
    else if (_003_) mac_result[12] <= _498_[12];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[13] <= 1'h0;
    else if (_003_) mac_result[13] <= _498_[13];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[14] <= 1'h0;
    else if (_003_) mac_result[14] <= _498_[14];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mac_result[15] <= 1'h0;
    else if (_003_) mac_result[15] <= _498_[15];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h0;
    else if (_002_) state[0] <= _497_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else if (_002_) state[1] <= _497_[1];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[2] <= 1'h0;
    else if (_002_) state[2] <= _494_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) neuron_idx[0] <= 1'h0;
    else if (_001_) neuron_idx[0] <= _496_[0];
  (* src = "dnn_accelerator.v:64.5-157.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) neuron_idx[1] <= 1'h0;
    else if (_001_) neuron_idx[1] <= _496_[1];
  (* module_not_derived = 32'd1 *)
  (* src = "dnn_accelerator.v:56.14-61.6" *)
  mac_unit mac_inst (
    .A(current_input),
    .B(mac_result),
    .C(mac_out),
    .W({ 1'h0, current_weight[6:0] })
  );
  assign _497_[2] = _494_[0];
  assign \bias_layer1[0]  = 16'h0064;
  assign \bias_layer1[1]  = 16'h00c8;
  assign \bias_layer1[2]  = 16'h012c;
  assign \bias_layer2[0]  = 16'h0096;
  assign \bias_layer2[1]  = 16'h00fa;
  assign current_weight[7] = 1'h0;
  assign done = valid;
  assign \weights_layer1[0]  = 8'h0a;
  assign \weights_layer1[10]  = 8'h20;
  assign \weights_layer1[11]  = 8'h2a;
  assign \weights_layer1[1]  = 8'h14;
  assign \weights_layer1[2]  = 8'h1e;
  assign \weights_layer1[3]  = 8'h28;
  assign \weights_layer1[4]  = 8'h0f;
  assign \weights_layer1[5]  = 8'h19;
  assign \weights_layer1[6]  = 8'h23;
  assign \weights_layer1[7]  = 8'h2d;
  assign \weights_layer1[8]  = 8'h0c;
  assign \weights_layer1[9]  = 8'h16;
  assign \weights_layer2[0]  = 8'h32;
  assign \weights_layer2[1]  = 8'h3c;
  assign \weights_layer2[2]  = 8'h46;
  assign \weights_layer2[3]  = 8'h37;
  assign \weights_layer2[4]  = 8'h41;
  assign \weights_layer2[5]  = 8'h4b;
  assign _493_ = state[2];
  assign _491_ = state[0];
  assign _492_ = state[1];
  assign _494_[0] = _466_;
  assign _489_ = rst_n;
  assign _309_ = neuron_idx[0];
  assign _310_ = neuron_idx[1];
  assign _292_ = input_idx[1];
  assign _006_ = _243_;
  assign _005_ = _242_;
  assign _497_[0] = _471_;
  assign _490_ = start;
  assign _000_ = _237_;
  assign _291_ = input_idx[0];
  assign _001_ = _238_;
  assign _002_ = _239_;
  assign _004_ = _241_;
  assign _003_ = _240_;
  assign _275_ = input_data_2[0];
  assign _283_ = input_data_3[0];
  assign _267_ = input_data_1[0];
  assign _259_ = input_data_0[0];
  assign current_input[0] = _244_;
  assign _276_ = input_data_2[1];
  assign _284_ = input_data_3[1];
  assign _268_ = input_data_1[1];
  assign _260_ = input_data_0[1];
  assign current_input[1] = _245_;
  assign _277_ = input_data_2[2];
  assign _285_ = input_data_3[2];
  assign _269_ = input_data_1[2];
  assign _261_ = input_data_0[2];
  assign current_input[2] = _246_;
  assign _278_ = input_data_2[3];
  assign _286_ = input_data_3[3];
  assign _270_ = input_data_1[3];
  assign _262_ = input_data_0[3];
  assign current_input[3] = _247_;
  assign _279_ = input_data_2[4];
  assign _287_ = input_data_3[4];
  assign _271_ = input_data_1[4];
  assign _263_ = input_data_0[4];
  assign current_input[4] = _248_;
  assign _280_ = input_data_2[5];
  assign _288_ = input_data_3[5];
  assign _272_ = input_data_1[5];
  assign _264_ = input_data_0[5];
  assign current_input[5] = _249_;
  assign _281_ = input_data_2[6];
  assign _289_ = input_data_3[6];
  assign _273_ = input_data_1[6];
  assign _265_ = input_data_0[6];
  assign current_input[6] = _250_;
  assign _282_ = input_data_2[7];
  assign _290_ = input_data_3[7];
  assign _274_ = input_data_1[7];
  assign _266_ = input_data_0[7];
  assign current_input[7] = _251_;
  assign current_weight[0] = _252_;
  assign current_weight[1] = _253_;
  assign current_weight[2] = _254_;
  assign current_weight[3] = _255_;
  assign current_weight[4] = _256_;
  assign current_weight[5] = _257_;
  assign current_weight[6] = _258_;
  assign _495_[0] = _467_;
  assign _495_[1] = _468_;
  assign _496_[0] = _469_;
  assign _496_[1] = _470_;
  assign _497_[1] = _472_;
  assign _293_ = mac_out[0];
  assign _498_[0] = _473_;
  assign _300_ = mac_out[1];
  assign _498_[1] = _480_;
  assign _301_ = mac_out[2];
  assign _498_[2] = _481_;
  assign _302_ = mac_out[3];
  assign _498_[3] = _482_;
  assign _303_ = mac_out[4];
  assign _498_[4] = _483_;
  assign _304_ = mac_out[5];
  assign _498_[5] = _484_;
  assign _305_ = mac_out[6];
  assign _498_[6] = _485_;
  assign _306_ = mac_out[7];
  assign _498_[7] = _486_;
  assign _307_ = mac_out[8];
  assign _498_[8] = _487_;
  assign _308_ = mac_out[9];
  assign _498_[9] = _488_;
  assign _294_ = mac_out[10];
  assign _498_[10] = _474_;
  assign _295_ = mac_out[11];
  assign _498_[11] = _475_;
  assign _296_ = mac_out[12];
  assign _498_[12] = _476_;
  assign _297_ = mac_out[13];
  assign _498_[13] = _477_;
  assign _298_ = mac_out[14];
  assign _498_[14] = _478_;
  assign _299_ = mac_out[15];
  assign _498_[15] = _479_;
endmodule

(* src = "mac_unit.v:5.1-21.10" *)
module mac_unit(A, W, B, C);
  (* src = "mac_unit.v:6.17-6.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "mac_unit.v:7.17-7.18" *)
  input [7:0] W;
  wire [7:0] W;
  (* src = "mac_unit.v:8.18-8.19" *)
  input [15:0] B;
  wire [15:0] B;
  (* src = "mac_unit.v:9.19-9.20" *)
  output [15:0] C;
  wire [15:0] C;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0434_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0435_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0436_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0437_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0438_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0439_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0440_;
  (* src = "mac_unit.v:6.17-6.18" *)
  wire _0441_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0442_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0443_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0444_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0445_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0446_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0447_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0448_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0449_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0450_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0451_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0452_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0453_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0454_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0455_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0456_;
  (* src = "mac_unit.v:8.18-8.19" *)
  wire _0457_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0458_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0459_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0460_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0461_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0462_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0463_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0464_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0465_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0466_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0467_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0468_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0469_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0470_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0471_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0472_;
  (* src = "mac_unit.v:9.19-9.20" *)
  wire _0473_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0474_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0475_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0476_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0477_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0478_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0479_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0480_;
  (* src = "mac_unit.v:7.17-7.18" *)
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  wire _0799_;
  wire _0800_;
  wire _0801_;
  wire _0802_;
  wire _0803_;
  wire _0804_;
  wire _0805_;
  wire _0806_;
  wire _0807_;
  wire _0808_;
  wire _0809_;
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  wire _0815_;
  wire _0816_;
  wire _0817_;
  wire _0818_;
  wire _0819_;
  wire _0820_;
  wire _0821_;
  wire _0822_;
  wire _0823_;
  wire _0824_;
  wire _0825_;
  wire _0826_;
  wire _0827_;
  wire _0828_;
  wire _0829_;
  wire _0830_;
  wire _0831_;
  wire _0832_;
  wire _0833_;
  wire _0834_;
  wire _0835_;
  wire _0836_;
  wire _0837_;
  wire _0838_;
  wire _0839_;
  wire _0840_;
  wire _0841_;
  wire _0842_;
  wire _0843_;
  wire _0844_;
  wire _0845_;
  wire _0846_;
  wire _0847_;
  wire _0848_;
  wire _0849_;
  wire _0850_;
  wire _0851_;
  wire _0852_;
  wire _0853_;
  wire _0854_;
  wire _0855_;
  wire _0856_;
  wire _0857_;
  wire _0858_;
  wire _0859_;
  wire _0860_;
  wire _0861_;
  wire _0862_;
  wire _0863_;
  wire _0864_;
  wire _0865_;
  wire _0866_;
  wire _0867_;
  wire _0868_;
  wire _0869_;
  wire _0870_;
  wire _0871_;
  wire _0872_;
  wire _0873_;
  wire _0874_;
  wire _0875_;
  wire _0876_;
  wire _0877_;
  wire _0878_;
  wire _0879_;
  wire _0880_;
  assign _0832_ = _0474_ & _0434_;
  assign _0833_ = ~(_0442_ & _0832_);
  assign _0458_ = _0442_ ^ _0832_;
  assign _0834_ = _0435_ & _0475_;
  assign _0835_ = ~(_0434_ & _0476_);
  assign _0836_ = ~(_0476_ & _0435_);
  assign _0837_ = ~(_0434_ & _0475_);
  assign _0838_ = _0836_ | _0837_;
  assign _0839_ = ~(_0834_ ^ _0835_);
  assign _0840_ = _0474_ & _0436_;
  assign _0841_ = ~(_0839_ & _0840_);
  assign _0842_ = ~(_0838_ & _0841_);
  assign _0843_ = _0474_ & _0437_;
  assign _0844_ = _0475_ & _0436_;
  assign _0845_ = _0476_ & _0436_;
  assign _0846_ = ~(_0834_ & _0845_);
  assign _0847_ = ~(_0836_ ^ _0844_);
  assign _0848_ = ~(_0843_ & _0847_);
  assign _0849_ = _0843_ ^ _0847_;
  assign _0850_ = _0842_ & _0849_;
  assign _0851_ = _0842_ ^ _0849_;
  assign _0852_ = _0434_ & _0477_;
  assign _0853_ = _0451_ & _0852_;
  assign _0854_ = ~(_0451_ ^ _0852_);
  assign _0855_ = _0851_ & ~(_0854_);
  assign _0856_ = ~(_0851_ ^ _0854_);
  assign _0857_ = _0474_ & _0435_;
  assign _0858_ = _0832_ & _0834_;
  assign _0859_ = _0839_ ^ _0840_;
  assign _0860_ = ~(_0858_ & _0859_);
  assign _0861_ = _0858_ ^ _0859_;
  assign _0862_ = ~(_0450_ & _0861_);
  assign _0863_ = ~(_0860_ & _0862_);
  assign _0864_ = _0856_ & _0863_;
  assign _0865_ = _0856_ ^ _0863_;
  assign _0866_ = ~(_0450_ ^ _0861_);
  assign _0867_ = ~(_0837_ ^ _0857_);
  assign _0868_ = ~(_0449_ & _0867_);
  assign _0869_ = ~(_0449_ ^ _0867_);
  assign _0870_ = _0833_ | _0869_;
  assign _0871_ = ~(_0868_ & _0870_);
  assign _0872_ = _0871_ & ~(_0866_);
  assign _0873_ = _0865_ & _0872_;
  assign _0467_ = _0865_ ^ _0872_;
  assign _0874_ = ~(_0846_ & _0848_);
  assign _0875_ = _0474_ & _0438_;
  assign _0876_ = _0475_ & _0437_;
  assign _0877_ = _0476_ & _0437_;
  assign _0878_ = ~(_0845_ & _0876_);
  assign _0879_ = _0845_ ^ _0876_;
  assign _0880_ = ~(_0875_ & _0879_);
  assign _0482_ = _0875_ ^ _0879_;
  assign _0483_ = _0874_ & _0482_;
  assign _0484_ = _0874_ ^ _0482_;
  assign _0485_ = ~(_0477_ & _0435_);
  assign _0486_ = _0434_ & _0478_;
  assign _0487_ = _0435_ & _0478_;
  assign _0488_ = _0852_ & _0487_;
  assign _0489_ = ~(_0485_ ^ _0486_);
  assign _0490_ = _0452_ & _0489_;
  assign _0491_ = ~(_0452_ ^ _0489_);
  assign _0492_ = _0853_ & ~(_0491_);
  assign _0493_ = ~(_0853_ ^ _0491_);
  assign _0494_ = _0484_ & _0493_;
  assign _0495_ = _0484_ ^ _0493_;
  assign _0496_ = ~(_0855_ & _0495_);
  assign _0497_ = _0855_ ^ _0495_;
  assign _0498_ = ~(_0850_ & _0497_);
  assign _0499_ = _0850_ ^ _0497_;
  assign _0500_ = ~(_0864_ & _0499_);
  assign _0501_ = _0864_ ^ _0499_;
  assign _0502_ = ~(_0873_ & _0501_);
  assign _0468_ = _0873_ ^ _0501_;
  assign _0503_ = ~(_0500_ & _0502_);
  assign _0504_ = ~(_0496_ & _0498_);
  assign _0505_ = _0492_ | _0494_;
  assign _0506_ = ~(_0878_ & _0880_);
  assign _0507_ = _0474_ & _0439_;
  assign _0508_ = _0475_ & _0438_;
  assign _0509_ = _0476_ & _0438_;
  assign _0510_ = ~(_0877_ & _0508_);
  assign _0511_ = _0877_ ^ _0508_;
  assign _0512_ = ~(_0507_ & _0511_);
  assign _0513_ = _0507_ ^ _0511_;
  assign _0514_ = ~(_0488_ & _0513_);
  assign _0515_ = _0488_ ^ _0513_;
  assign _0516_ = ~(_0506_ & _0515_);
  assign _0517_ = _0506_ ^ _0515_;
  assign _0518_ = _0477_ & _0436_;
  assign _0519_ = _0434_ & _0479_;
  assign _0520_ = ~(_0435_ & _0479_);
  assign _0521_ = ~(_0487_ & _0519_);
  assign _0522_ = _0487_ ^ _0519_;
  assign _0523_ = ~(_0518_ & _0522_);
  assign _0524_ = _0518_ ^ _0522_;
  assign _0525_ = _0453_ & _0524_;
  assign _0526_ = ~(_0453_ ^ _0524_);
  assign _0527_ = _0490_ & ~(_0526_);
  assign _0528_ = ~(_0490_ ^ _0526_);
  assign _0529_ = _0517_ & _0528_;
  assign _0530_ = _0517_ ^ _0528_;
  assign _0531_ = ~(_0505_ & _0530_);
  assign _0532_ = _0505_ ^ _0530_;
  assign _0533_ = ~(_0483_ & _0532_);
  assign _0534_ = _0483_ ^ _0532_;
  assign _0535_ = ~(_0504_ & _0534_);
  assign _0536_ = _0504_ ^ _0534_;
  assign _0537_ = ~(_0503_ & _0536_);
  assign _0469_ = _0503_ ^ _0536_;
  assign _0538_ = ~(_0535_ & _0537_);
  assign _0539_ = ~(_0531_ & _0533_);
  assign _0540_ = ~(_0514_ & _0516_);
  assign _0541_ = _0527_ | _0529_;
  assign _0542_ = ~(_0510_ & _0512_);
  assign _0543_ = _0474_ & _0440_;
  assign _0544_ = _0475_ & _0439_;
  assign _0545_ = _0476_ & _0439_;
  assign _0546_ = ~(_0509_ & _0544_);
  assign _0547_ = _0509_ ^ _0544_;
  assign _0548_ = ~(_0543_ & _0547_);
  assign _0549_ = _0543_ ^ _0547_;
  assign _0550_ = ~(_0521_ & _0523_);
  assign _0551_ = ~(_0549_ & _0550_);
  assign _0552_ = _0549_ ^ _0550_;
  assign _0553_ = ~(_0542_ & _0552_);
  assign _0554_ = _0542_ ^ _0552_;
  assign _0555_ = _0477_ & _0437_;
  assign _0556_ = _0436_ & _0478_;
  assign _0557_ = _0436_ & _0479_;
  assign _0558_ = ~(_0487_ & _0557_);
  assign _0559_ = ~(_0520_ ^ _0556_);
  assign _0560_ = ~(_0555_ & _0559_);
  assign _0561_ = _0555_ ^ _0559_;
  assign _0562_ = _0434_ & _0480_;
  assign _0563_ = _0454_ & _0562_;
  assign _0564_ = ~(_0454_ ^ _0562_);
  assign _0565_ = _0561_ & ~(_0564_);
  assign _0566_ = ~(_0561_ ^ _0564_);
  assign _0567_ = ~(_0525_ & _0566_);
  assign _0568_ = _0525_ ^ _0566_;
  assign _0569_ = ~(_0554_ & _0568_);
  assign _0570_ = _0554_ ^ _0568_;
  assign _0571_ = ~(_0541_ & _0570_);
  assign _0572_ = _0541_ ^ _0570_;
  assign _0573_ = ~(_0540_ & _0572_);
  assign _0574_ = _0540_ ^ _0572_;
  assign _0575_ = ~(_0539_ & _0574_);
  assign _0576_ = _0539_ ^ _0574_;
  assign _0577_ = ~(_0538_ & _0576_);
  assign _0470_ = _0538_ ^ _0576_;
  assign _0578_ = ~(_0575_ & _0577_);
  assign _0579_ = ~(_0571_ & _0573_);
  assign _0580_ = ~(_0551_ & _0553_);
  assign _0581_ = ~(_0567_ & _0569_);
  assign _0582_ = ~(_0546_ & _0548_);
  assign _0583_ = _0474_ & _0441_;
  assign _0584_ = ~(_0475_ & _0440_);
  assign _0585_ = _0476_ & _0440_;
  assign _0586_ = ~(_0544_ & _0585_);
  assign _0587_ = ~(_0545_ ^ _0584_);
  assign _0588_ = ~(_0583_ & _0587_);
  assign _0589_ = _0583_ ^ _0587_;
  assign _0590_ = ~(_0558_ & _0560_);
  assign _0591_ = ~(_0589_ & _0590_);
  assign _0592_ = _0589_ ^ _0590_;
  assign _0593_ = ~(_0582_ & _0592_);
  assign _0594_ = _0582_ ^ _0592_;
  assign _0595_ = _0477_ & _0438_;
  assign _0596_ = _0437_ & _0478_;
  assign _0597_ = _0437_ & _0479_;
  assign _0598_ = ~(_0557_ & _0596_);
  assign _0599_ = _0557_ ^ _0596_;
  assign _0600_ = ~(_0595_ & _0599_);
  assign _0601_ = _0595_ ^ _0599_;
  assign _0602_ = _0435_ & _0480_;
  assign _0603_ = _0434_ & _0481_;
  assign _0604_ = _0455_ & _0603_;
  assign _0605_ = ~(_0455_ ^ _0603_);
  assign _0606_ = _0602_ & ~(_0605_);
  assign _0607_ = ~(_0602_ ^ _0605_);
  assign _0608_ = ~(_0563_ & _0607_);
  assign _0609_ = _0563_ ^ _0607_;
  assign _0610_ = ~(_0601_ & _0609_);
  assign _0611_ = _0601_ ^ _0609_;
  assign _0612_ = ~(_0565_ & _0611_);
  assign _0613_ = _0565_ ^ _0611_;
  assign _0614_ = ~(_0594_ & _0613_);
  assign _0615_ = _0594_ ^ _0613_;
  assign _0616_ = ~(_0581_ & _0615_);
  assign _0617_ = _0581_ ^ _0615_;
  assign _0618_ = ~(_0580_ & _0617_);
  assign _0619_ = _0580_ ^ _0617_;
  assign _0620_ = ~(_0579_ & _0619_);
  assign _0621_ = _0579_ ^ _0619_;
  assign _0622_ = ~(_0578_ & _0621_);
  assign _0471_ = _0578_ ^ _0621_;
  assign _0623_ = ~(_0620_ & _0622_);
  assign _0624_ = ~(_0616_ & _0618_);
  assign _0625_ = ~(_0591_ & _0593_);
  assign _0626_ = ~(_0612_ & _0614_);
  assign _0627_ = ~(_0586_ & _0588_);
  assign _0628_ = ~(_0598_ & _0600_);
  assign _0629_ = ~(_0475_ & _0441_);
  assign _0630_ = ~(_0585_ ^ _0629_);
  assign _0631_ = ~(_0628_ & _0630_);
  assign _0632_ = _0628_ ^ _0630_;
  assign _0633_ = ~(_0627_ & _0632_);
  assign _0634_ = _0627_ ^ _0632_;
  assign _0635_ = ~(_0608_ & _0610_);
  assign _0636_ = _0477_ & _0439_;
  assign _0637_ = _0478_ & _0438_;
  assign _0638_ = _0438_ & _0479_;
  assign _0639_ = ~(_0597_ & _0637_);
  assign _0640_ = _0597_ ^ _0637_;
  assign _0641_ = ~(_0636_ & _0640_);
  assign _0642_ = _0636_ ^ _0640_;
  assign _0643_ = _0604_ | _0606_;
  assign _0644_ = _0436_ & _0480_;
  assign _0645_ = _0435_ & _0481_;
  assign _0646_ = _0456_ & _0645_;
  assign _0647_ = ~(_0456_ ^ _0645_);
  assign _0648_ = _0644_ & ~(_0647_);
  assign _0649_ = ~(_0644_ ^ _0647_);
  assign _0650_ = ~(_0643_ & _0649_);
  assign _0651_ = _0643_ ^ _0649_;
  assign _0652_ = ~(_0642_ & _0651_);
  assign _0653_ = _0642_ ^ _0651_;
  assign _0654_ = ~(_0635_ & _0653_);
  assign _0655_ = _0635_ ^ _0653_;
  assign _0656_ = ~(_0634_ & _0655_);
  assign _0657_ = _0634_ ^ _0655_;
  assign _0658_ = ~(_0626_ & _0657_);
  assign _0659_ = _0626_ ^ _0657_;
  assign _0660_ = ~(_0625_ & _0659_);
  assign _0661_ = _0625_ ^ _0659_;
  assign _0662_ = ~(_0624_ & _0661_);
  assign _0663_ = _0624_ ^ _0661_;
  assign _0664_ = ~(_0623_ & _0663_);
  assign _0472_ = _0623_ ^ _0663_;
  assign _0665_ = ~(_0662_ & _0664_);
  assign _0666_ = ~(_0658_ & _0660_);
  assign _0667_ = ~(_0631_ & _0633_);
  assign _0668_ = ~(_0654_ & _0656_);
  assign _0669_ = ~(_0650_ & _0652_);
  assign _0670_ = _0477_ & _0440_;
  assign _0671_ = _0478_ & _0439_;
  assign _0672_ = _0479_ & _0439_;
  assign _0673_ = ~(_0638_ & _0671_);
  assign _0674_ = _0638_ ^ _0671_;
  assign _0675_ = ~(_0670_ & _0674_);
  assign _0676_ = _0670_ ^ _0674_;
  assign _0677_ = _0646_ | _0648_;
  assign _0678_ = _0437_ & _0480_;
  assign _0679_ = _0436_ & _0481_;
  assign _0680_ = _0457_ & _0679_;
  assign _0681_ = ~(_0457_ ^ _0679_);
  assign _0682_ = _0678_ & ~(_0681_);
  assign _0683_ = ~(_0678_ ^ _0681_);
  assign _0684_ = ~(_0677_ & _0683_);
  assign _0685_ = _0677_ ^ _0683_;
  assign _0686_ = ~(_0676_ & _0685_);
  assign _0687_ = _0676_ ^ _0685_;
  assign _0688_ = ~(_0669_ & _0687_);
  assign _0689_ = _0669_ ^ _0687_;
  assign _0690_ = _0639_ & _0641_;
  assign _0691_ = _0476_ & _0441_;
  assign _0692_ = _0584_ & _0691_;
  assign _0693_ = ~(_0690_ ^ _0692_);
  assign _0694_ = ~(_0689_ & _0693_);
  assign _0695_ = _0689_ ^ _0693_;
  assign _0696_ = ~(_0668_ & _0695_);
  assign _0697_ = _0668_ ^ _0695_;
  assign _0698_ = ~(_0667_ & _0697_);
  assign _0699_ = _0667_ ^ _0697_;
  assign _0700_ = ~(_0666_ & _0699_);
  assign _0701_ = _0666_ ^ _0699_;
  assign _0702_ = ~(_0665_ & _0701_);
  assign _0473_ = _0665_ ^ _0701_;
  assign _0703_ = ~(_0700_ & _0702_);
  assign _0704_ = ~(_0696_ & _0698_);
  assign _0705_ = ~(_0688_ & _0694_);
  assign _0706_ = ~(_0673_ & _0675_);
  assign _0707_ = ~(_0684_ & _0686_);
  assign _0708_ = _0477_ & _0441_;
  assign _0709_ = _0478_ & _0440_;
  assign _0710_ = ~(_0479_ & _0440_);
  assign _0711_ = ~(_0672_ & _0709_);
  assign _0712_ = _0672_ ^ _0709_;
  assign _0713_ = ~(_0708_ & _0712_);
  assign _0714_ = _0708_ ^ _0712_;
  assign _0715_ = _0680_ | _0682_;
  assign _0716_ = _0438_ & _0480_;
  assign _0717_ = _0437_ & _0481_;
  assign _0718_ = _0443_ & _0717_;
  assign _0719_ = ~(_0443_ ^ _0717_);
  assign _0720_ = _0716_ & ~(_0719_);
  assign _0721_ = ~(_0716_ ^ _0719_);
  assign _0722_ = ~(_0715_ & _0721_);
  assign _0723_ = _0715_ ^ _0721_;
  assign _0724_ = ~(_0714_ & _0723_);
  assign _0725_ = _0714_ ^ _0723_;
  assign _0726_ = ~(_0707_ & _0725_);
  assign _0727_ = _0707_ ^ _0725_;
  assign _0728_ = ~(_0706_ & _0727_);
  assign _0729_ = _0706_ ^ _0727_;
  assign _0730_ = ~(_0705_ & _0729_);
  assign _0731_ = _0705_ ^ _0729_;
  assign _0732_ = ~(_0584_ & _0690_);
  assign _0733_ = _0691_ & _0732_;
  assign _0734_ = ~(_0731_ & _0733_);
  assign _0735_ = _0731_ ^ _0733_;
  assign _0736_ = ~(_0704_ & _0735_);
  assign _0737_ = _0704_ ^ _0735_;
  assign _0738_ = ~(_0703_ & _0737_);
  assign _0459_ = _0703_ ^ _0737_;
  assign _0739_ = ~(_0736_ & _0738_);
  assign _0740_ = ~(_0730_ & _0734_);
  assign _0741_ = ~(_0726_ & _0728_);
  assign _0742_ = ~(_0711_ & _0713_);
  assign _0743_ = ~(_0722_ & _0724_);
  assign _0744_ = _0478_ & _0441_;
  assign _0745_ = _0479_ & _0441_;
  assign _0746_ = _0709_ & _0745_;
  assign _0747_ = ~(_0710_ ^ _0744_);
  assign _0748_ = _0718_ | _0720_;
  assign _0749_ = _0439_ & _0480_;
  assign _0750_ = _0438_ & _0481_;
  assign _0751_ = _0444_ & _0750_;
  assign _0752_ = ~(_0444_ ^ _0750_);
  assign _0753_ = _0749_ & ~(_0752_);
  assign _0754_ = ~(_0749_ ^ _0752_);
  assign _0755_ = ~(_0748_ & _0754_);
  assign _0756_ = _0748_ ^ _0754_;
  assign _0757_ = ~(_0747_ & _0756_);
  assign _0758_ = _0747_ ^ _0756_;
  assign _0759_ = ~(_0743_ & _0758_);
  assign _0760_ = _0743_ ^ _0758_;
  assign _0761_ = ~(_0742_ & _0760_);
  assign _0762_ = _0742_ ^ _0760_;
  assign _0763_ = _0741_ & _0762_;
  assign _0764_ = _0741_ ^ _0762_;
  assign _0765_ = ~(_0740_ & _0764_);
  assign _0766_ = _0740_ ^ _0764_;
  assign _0767_ = ~(_0739_ & _0766_);
  assign _0460_ = _0739_ ^ _0766_;
  assign _0768_ = ~(_0765_ & _0767_);
  assign _0769_ = ~(_0759_ & _0761_);
  assign _0770_ = ~(_0755_ & _0757_);
  assign _0771_ = _0751_ | _0753_;
  assign _0772_ = _0480_ & _0440_;
  assign _0773_ = _0439_ & _0481_;
  assign _0774_ = _0445_ & _0773_;
  assign _0775_ = ~(_0445_ ^ _0773_);
  assign _0776_ = _0772_ & ~(_0775_);
  assign _0777_ = ~(_0772_ ^ _0775_);
  assign _0778_ = ~(_0771_ & _0777_);
  assign _0779_ = _0771_ ^ _0777_;
  assign _0780_ = ~(_0745_ & _0779_);
  assign _0781_ = _0745_ ^ _0779_;
  assign _0782_ = ~(_0770_ & _0781_);
  assign _0783_ = _0770_ ^ _0781_;
  assign _0784_ = ~(_0746_ & _0783_);
  assign _0785_ = _0746_ ^ _0783_;
  assign _0786_ = _0769_ & _0785_;
  assign _0787_ = _0769_ ^ _0785_;
  assign _0788_ = ~(_0763_ & _0787_);
  assign _0789_ = _0763_ ^ _0787_;
  assign _0790_ = ~(_0768_ & _0789_);
  assign _0461_ = _0768_ ^ _0789_;
  assign _0791_ = ~(_0788_ & _0790_);
  assign _0792_ = ~(_0782_ & _0784_);
  assign _0793_ = ~(_0778_ & _0780_);
  assign _0794_ = _0774_ | _0776_;
  assign _0795_ = ~(_0480_ & _0441_);
  assign _0796_ = _0440_ & _0481_;
  assign _0797_ = ~(_0446_ & _0796_);
  assign _0798_ = ~(_0446_ ^ _0796_);
  assign _0799_ = _0795_ | _0798_;
  assign _0800_ = _0795_ ^ _0798_;
  assign _0801_ = ~(_0794_ & _0800_);
  assign _0802_ = _0794_ | _0800_;
  assign _0803_ = ~(_0801_ & _0802_);
  assign _0804_ = ~(_0793_ & _0802_);
  assign _0805_ = _0793_ & ~(_0803_);
  assign _0806_ = ~(_0793_ ^ _0803_);
  assign _0807_ = _0792_ & _0806_;
  assign _0808_ = _0792_ ^ _0806_;
  assign _0809_ = ~(_0786_ & _0808_);
  assign _0810_ = _0786_ ^ _0808_;
  assign _0811_ = ~(_0791_ & _0810_);
  assign _0462_ = _0791_ ^ _0810_;
  assign _0812_ = ~(_0809_ & _0811_);
  assign _0813_ = _0797_ & _0799_;
  assign _0814_ = _0481_ & _0441_;
  assign _0815_ = ~(_0447_ & _0814_);
  assign _0816_ = ~(_0447_ ^ _0814_);
  assign _0817_ = _0813_ | _0816_;
  assign _0818_ = ~(_0813_ & _0816_);
  assign _0819_ = _0817_ & _0818_;
  assign _0820_ = _0801_ & _0804_;
  assign _0821_ = ~(_0819_ ^ _0820_);
  assign _0822_ = ~(_0807_ & _0821_);
  assign _0823_ = _0807_ ^ _0821_;
  assign _0824_ = ~(_0812_ & _0823_);
  assign _0463_ = _0812_ ^ _0823_;
  assign _0825_ = _0822_ & _0824_;
  assign _0826_ = _0805_ & _0819_;
  assign _0827_ = ~(_0801_ & _0817_);
  assign _0828_ = _0818_ & _0827_;
  assign _0829_ = ~(_0448_ ^ _0815_);
  assign _0830_ = ~(_0828_ ^ _0829_);
  assign _0831_ = ~(_0826_ ^ _0830_);
  assign _0464_ = ~(_0825_ ^ _0831_);
  assign _0466_ = ~(_0866_ ^ _0871_);
  assign _0465_ = _0833_ ^ _0869_;
  assign _0474_ = W[0];
  assign _0434_ = A[0];
  assign _0442_ = B[0];
  assign C[0] = _0458_;
  assign _0477_ = W[3];
  assign _0451_ = B[3];
  assign _0476_ = W[2];
  assign _0435_ = A[1];
  assign _0475_ = W[1];
  assign _0436_ = A[2];
  assign _0437_ = A[3];
  assign _0450_ = B[2];
  assign _0449_ = B[1];
  assign C[3] = _0467_;
  assign _0478_ = W[4];
  assign _0452_ = B[4];
  assign _0438_ = A[4];
  assign C[4] = _0468_;
  assign _0479_ = W[5];
  assign _0453_ = B[5];
  assign _0439_ = A[5];
  assign C[5] = _0469_;
  assign _0480_ = W[6];
  assign _0454_ = B[6];
  assign _0440_ = A[6];
  assign C[6] = _0470_;
  assign _0481_ = W[7];
  assign _0455_ = B[7];
  assign _0441_ = A[7];
  assign C[7] = _0471_;
  assign _0456_ = B[8];
  assign C[8] = _0472_;
  assign _0457_ = B[9];
  assign C[9] = _0473_;
  assign _0443_ = B[10];
  assign C[10] = _0459_;
  assign _0444_ = B[11];
  assign C[11] = _0460_;
  assign _0445_ = B[12];
  assign C[12] = _0461_;
  assign _0446_ = B[13];
  assign C[13] = _0462_;
  assign _0447_ = B[14];
  assign C[14] = _0463_;
  assign _0448_ = B[15];
  assign C[15] = _0464_;
  assign C[2] = _0466_;
  assign C[1] = _0465_;
endmodule
